services:
  triton:
    image: nvcr.io/nvidia/tritonserver:25.01-py3
    volumes:
      - ./model-repo:/models
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${CUDA_VISIBLE_DEVICES}']
              capabilities: [gpu]
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      tritonserver
      --model-repository=/models
      --grpc-port=8001
      --http-port=8000
  preprocessor:
    build:
      context: preprocessor/
      dockerfile: Dockerfile
    volumes:
      - ./sample:/sample
      - ./out:/out
    ports:
      - 8080:8080
    environment:
      - PYTHONUNBUFFERED=1
    # entrypoint is python main.py
    # TODO: tune batch size, concurrent calls, tile readers, queue depth
    command: >
      --model_name virchow
      --predictor_host triton:8001
      --protocol=v2
      --tile_batch 512
      --concurrent_calls_to_predictor 8
      --num_tile_readers 4
      --queue_depth 16
    depends_on:
      - triton
